spring:
  application:
    name: security-tests
  datasource:
    password: postgres123
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:32137/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: false
  security:
    user:
      name: admin
      password: admin123
  liquibase:
    change-log: changelog-master.xml
    enabled: 'true'
server:
  port: 2137
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration: 1 #1h in minutes